name: LiSCa_Net
stage: 1


training:
  checkpoint_dir: ./checkpoints/
  init_lr: 0.001
  loss: 1*self_L1
  max_epoch: 100

  dl:
    batch_num: 30
    shuffle: True
    num_workers: 0
    pin_memory: True

  opt:
    type: Adam
    Adam:
      betas: [0.9, 0.999]
    SGD:
      momentum: 0.9
      weight_decay: 0.0001
    AdamW:
      betas: [0.9, 0.999]
      weight_decay: 0.0001

  scheduler:
    enable: False
    type: step
    step:
      step_size: 5
      gamma: 0.8
    linear:
      step_size: 20
      gamma: 0.1

validation:
  val: False
  dl:
    num_workers: 0
    pin_memory: True
    batch_size: 8192

  start_epoch: 1
  interval_epoch: 1

testing:
  dl:
    num_workers: 0
    pin_memory: True
    batch_size: 8192

  ckpt_epoch: -1
  pretrained:

model:
  type: BSN_1D

  BSN_1D:
    nch_in: 1
    nch_out: 1
    blindspot: True
    zero_output_weights: False
    nch_ker: 12
    depth: 6

checkpoint:
  save: True
  start_epoch: 40
  interval_epoch: 50

log:
  interval_iter: 80
  interval_epoch: 10








